### ISSUE TITLE
Invalid parameter 'app_versions'

### ISSUE THREAD

**Issue by josex2r** [bugsnag/bugsnag-api#10]
Hi, I'm trying to count the errors of my application using the bugsnag API.

Currently It's impossible to me to filter the errors by application version, the API responses with an error `{"error":"invalid parameter: app_versions"}`.

The endpoint who is failing is `/projects/XXXXXXXXXXX/errors?severity=error&status=open&release_stages=production&app_versions=gte4.8.4&per_page=100`

I think the request are ok because I can retrieve data from other endpoints like `events` or removing the `app_versions` parameter from the previous example.

¿Is `app_versions` working?

Thanks

**Comment by duncanhewett** [comment]
Hi @josex2r,

Thanks for reporting this.  We had an issue with the `app_versions` field which has now been fixed - sorry for the inconvenience.

In future you will most likely get a quicker response to this kind of issue by contacting support (support@bugsnag.com).

**Comment by josex2r** [comment]
That was fast 👍 

Thanks!
