### ISSUE TITLE
missing assigned_user_id in Errors API 

### ISSUE THREAD

**Issue by adipasquale** [bugsnag/bugsnag-api#9]
Could you add the `assigned_user_id` in the list of returned fields from the Errors API ? 

I desperately need it for a custom integration that will automatically ping my team members with long standing `in_progress` tickets.

**Comment by marcgg** [comment]
👍  

Not having this removes the possibility to build any kind of deep integration with bugsnag since we are not able to link our internal workflow and our "bugsnag workflow". The Github integration helps, but in more than one case we need something more complex than this.

**Comment by martin308** [comment]
Hi @adipasquale @marcgg, this seems like a great addition to the API. I am looking into adding this and will let you know when it is live

**Comment by martin308** [comment]
@adipasquale @marcgg you should be able to see this field populated now

**Comment by adipasquale** [comment]
Great ! thanks for the quick and efficient reply 👍
